// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4LkSdcqOFaCc8Zwqn6OE6-wbSsxXxUQ',
    appId: '1:200711307324:web:b28a34d8fdbe97fda90339',
    messagingSenderId: '200711307324',
    projectId: 'totalx-b967a',
    authDomain: 'totalx-b967a.firebaseapp.com',
    storageBucket: 'totalx-b967a.firebasestorage.app',
    measurementId: 'G-1J3R357S0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAdhk8b9Gh-6msU_zhRxDbvEGwd6D4pJQ',
    appId: '1:200711307324:android:6b2e7dd7011d9976a90339',
    messagingSenderId: '200711307324',
    projectId: 'totalx-b967a',
    storageBucket: 'totalx-b967a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJrrfa-1e7XRcMUdjIoWvuuUhbDGjUBU',
    appId: '1:200711307324:ios:66f52fe0c7bbd5e9a90339',
    messagingSenderId: '200711307324',
    projectId: 'totalx-b967a',
    storageBucket: 'totalx-b967a.firebasestorage.app',
    iosClientId: '200711307324-prpico4nsfbbdnr3fo2lpvia56tp4c2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJrrfa-1e7XRcMUdjIoWvuuUhbDGjUBU',
    appId: '1:200711307324:ios:66f52fe0c7bbd5e9a90339',
    messagingSenderId: '200711307324',
    projectId: 'totalx-b967a',
    storageBucket: 'totalx-b967a.firebasestorage.app',
    iosClientId: '200711307324-prpico4nsfbbdnr3fo2lpvia56tp4c2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4LkSdcqOFaCc8Zwqn6OE6-wbSsxXxUQ',
    appId: '1:200711307324:web:67fef1f8b0923d65a90339',
    messagingSenderId: '200711307324',
    projectId: 'totalx-b967a',
    authDomain: 'totalx-b967a.firebaseapp.com',
    storageBucket: 'totalx-b967a.firebasestorage.app',
    measurementId: 'G-29DYNX3277',
  );
}
